### PR TITLE
Changed ls from printing full path length to individual files

### PR DESCRIPTION
**Pull request by abimek**
Because ls printed out the full path it was really verbose, so i removed that so now it will only print out the file names

### CODE REVIEW

**Comment by Jviguy** [comment]
How does this look with recursive ls does it print dir/file?

**Comment by abimekuriya** [comment]
Just updates it, now it will print in the format 

image

**Comment by Jviguy** [comment]
Looks great to me! One last thing maybe make a flag parameter enabling verbose output just for the utility of it `ls -v` something like that?

**Comment by abimekuriya** [comment]
Great Idea

**Comment by Prim69** [comment]
you can remove the clone from the as_path, it's not needed

**Comment by abimekuriya** [comment]
I assumed that strip_prefix took ownership of Path but it takes a reference instead. I'll update this and get it working once i get home, 

Also, does dev_term have functionality for flags like -v without a value associated so the user wouldn't have to do "-v true"

**Pull request merged**
